config/routes.rb
Rails.application.routes.draw do
  resources :tittles
   #root "articles#index"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tittle.rb
class Tittle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tittles_controller.rb
class TittlesController < ApplicationController
  before_action :set_tittle, only: %i[ show edit update destroy ]

  # GET /tittles or /tittles.json
  def index
    @tittles = Tittle.all
  end

  # GET /tittles/1 or /tittles/1.json
  def show
  end

  # GET /tittles/new
  def new
    @tittle = Tittle.new
  end

  # GET /tittles/1/edit
  def edit
  end

  # POST /tittles or /tittles.json
  def create
    @tittle = Tittle.new(tittle_params)

    respond_to do |format|
      if @tittle.save
        format.html { redirect_to tittle_url(@tittle), notice: "Tittle was successfully created." }
        format.json { render :show, status: :created, location: @tittle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tittle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tittles/1 or /tittles/1.json
  def update
    respond_to do |format|
      if @tittle.update(tittle_params)
        format.html { redirect_to tittle_url(@tittle), notice: "Tittle was successfully updated." }
        format.json { render :show, status: :ok, location: @tittle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tittle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tittles/1 or /tittles/1.json
  def destroy
    @tittle.destroy

    respond_to do |format|
      format.html { redirect_to tittles_url, notice: "Tittle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tittle
      @tittle = Tittle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tittle_params
      params.require(:tittle).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tittles_helper.rb
module TittlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tittles/_form.html.erb
<%= form_with(model: tittle) do |form| %>
  <% if tittle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tittle.errors.count, "error") %> prohibited this tittle from being saved:</h2>

      <ul>
        <% tittle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tittles/_tittle.html.erb
<div id="<%= dom_id tittle %>">
  <p>
    <strong>Content:</strong>
    <%= tittle.content %>
  </p>

</div>

app/views/tittles/edit.html.erb
<h1>Editing tittle</h1>

<%= render "form", tittle: @tittle %>

<br>

<div>
  <%= link_to "Show this tittle", @tittle %> |
  <%= link_to "Back to tittles", tittles_path %>
</div>

app/views/tittles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tittles</h1>

<div id="tittles">
  <% @tittles.each do |tittle| %>
    <%= render tittle %>
    <p>
      <%= link_to "Show this tittle", tittle %>
    </p>
  <% end %>
</div>

<%= link_to "New tittle", new_tittle_path %>

app/views/tittles/new.html.erb
<h1>New tittle</h1>

<%= render "form", tittle: @tittle %>

<br>

<div>
  <%= link_to "Back to tittles", tittles_path %>
</div>

app/views/tittles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tittle %>

<div>
  <%= link_to "Edit this tittle", edit_tittle_path(@tittle) %> |
  <%= link_to "Back to tittles", tittles_path %>

  <%= button_to "Destroy this tittle", @tittle, method: :delete %>
</div>